### ISSUE TITLE
Adding auth_providers prevents logging into IDE with HA user/password

### ISSUE THREAD

**Issue by mlevit** [hassio-addons/repository#138]
# Problem/Motivation

> Cannot log into IDE add-on when `auth_providers` is added under `homeassistant`.

## Expected behavior

> Can log in using HA username and password

## Actual behavior

> Access deniad

## Steps to reproduce

> Add the following

```
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 192.168.1.0/24
```

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
